SHARED_DATA = "data"
MENTOR_DATA = "{}/data"
MENTOR_BUILD = "{}/build"
MENTOR_VIDEOS = "videos/{}"
SESSION_DATA = "recordings/session{}"
SESSION_OUTPUT = "out"
AUDIOCHUNKS = "audiochunks"
WEB_VIDEOS = "web"
MOBILE_VIDEOS = "mobile"
STATIC_VIDEOS = "recordings/static-videos"

DATA_FILENAME = "part{}_{}"
VIDEO_FILE = "video.mp4"
AUDIO_FILE = "audio.wav"
TIMESTAMP_FILE = "timestamps.csv"
TOPIC_MAP = "master_topic_map.csv"
PARAPHRASE_MAP = "master_paraphrase_map.csv"
PU_FILENAME = "prompts_utterances.csv"
QPA_FILENAME = "questions_paraphrases_answers.csv"
TRANSCRIPT_FILE = "transcript.csv"
UTTERANCE_DATA = "utterance_data.csv"
CLASSIFIER_DATA = "classifier_data.csv"
METADATA = "metadata.csv"

# TODO: Fix this. We shouldn't hardcode static video names
IDLE_FILE = "idle.mp4"
MENTOR_INTRO = "{}_a1_1_1.mp4"
